language: node_js
node_js:
  - "8"
services:
  - postgresql

postgres:
  user: process.env.USER
  host: process.env.HOST
  database: process.env.DB_DATABASE
  password: process.env.DB_PASSWORD
  port: process.env.DB_PORT
  userPass: process.env.USER_PASSWORD
  adminPass: process.env.ADMIN_PASSWORD
  

before_install:
  - npm install -g npm@latest

before_script:
  - psql -c 'create database mtracker;' -U postgres

script:
  - npm test

after_success:
-  npm run coverage