language: node_js
node_js:
  - "8"
services:
  - postgresql

env:
  DB_HOST=localhost
  DB_PORT=5432
  DB_DATABASE=mtracker
  DB_USERNAME=postgres
  DB_PASSWORD=
  ADMIN_PASSWORD=testadmin
  USER_PASSWORD=testuser
  JWT_KEY=testkey

before_install:
  - npm install -g npm@latest

before_script:
  - psql -c 'create database mtracker;' -U postgres

script:
  - npm test

after_success:
-  npm run coverage