language: node_js
node_js:
  - "8"
services:
  - postgresql

env:
  DATABASE_URL=postgres://ownohaap:pxQ3Rq_sqG9OclEYka9t0hWKupwnc-nt@pellefant.db.elephantsql.com:5432/ownohaap
  ADMIN_PASSWORD=testadmin
  USER_PASSWORD=testuser
  JWT_KEY=testkey

before_install:
  - npm install -g npm@latest

before_script:
  - psql -c 'create database mtracker;' -U postgres

script:
  - npm test

after_success:
-  npm run coverage